In [ ]:
!pip install git+https://github.com/endgameinc/ember.git


  Cloning https://github.com/endgameinc/ember.git to c:\users\user\appdata\local\temp\pip-req-build-_9e0gcdr
  Created wheel for ember: filename=ember-0.1.0-py3-none-any.whl size=12407 sha256=36414adb95332fe713a415e1d541e4ff87e1f7b8f57acc4fccc92a77e602c7b7
  Stored in directory: C:\Users\user\AppData\Local\Temp\pip-ephem-wheel-cache-nqs43e2t\wheels\56\5f\88\ca30c00c701a2f7fd775c1b6254b9c14fdd3ad1ffcedfd42ef
Successfully built ember


  Running command git clone -q https://github.com/endgameinc/ember.git 'C:\Users\user\AppData\Local\Temp\pip-req-build-_9e0gcdr'


In [ ]:
!pip install -r requirements.txt
!python setup.py install
!pip install ember

running install
running bdist_egg
running egg_info
writing ember.egg-info\PKG-INFO
writing dependency_links to ember.egg-info\dependency_links.txt
writing requirements to ember.egg-info\requires.txt
writing top-level names to ember.egg-info\top_level.txt
reading manifest file 'ember.egg-info\SOURCES.txt'
writing manifest file 'ember.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\ember
copying build\lib\ember\features.py -> build\bdist.win-amd64\egg\ember
copying build\lib\ember\__init__.py -> build\bdist.win-amd64\egg\ember
byte-compiling build\bdist.win-amd64\egg\ember\features.py to features.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\ember\__init__.py to __init__.cpython-37.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying ember.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying ember.egg-info\SOURCES.txt -> build\bdist

zip_safe flag not set; analyzing archive contents...


In [ ]:
!pip install altair
!pip install altair vega_datasets

In [ ]:
import os
import numpy as np
import requests
import pandas as pd
import ember
import altair as alt
import lightgbm as lgb
import matplotlib.pylab as plt
from tqdm import tqdm
from os import listdir
from keras import optimizers, Input, Model
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Activation, GlobalMaxPooling1D, Input, Embedding, Multiply
from keras.models import Model, load_model
from keras import backend as K
from keras import metrics
from keras.optimizers import SGD
from keras.callbacks import LearningRateScheduler
from keras.callbacks import EarlyStopping
import time

  

Using TensorFlow backend.


In [ ]:
start = time.process_time()
!python train_ember.py "dataset/"
!python classify_binaries.py -m "dataset/" BINARIES
print(time.process_time() - start)

Training LightGBM model
[LightGBM] [Warning] objective is set=binary, application=binary will be ignored. Current value: objective=binary
[LightGBM] [Warning] objective is set=binary, application=binary will be ignored. Current value: objective=binary
[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] Number of positive: 286949, number of negative: 325640
[LightGBM] [Info] Total Bins 205555
[LightGBM] [Info] Number of data: 612589, number of used features: 2322
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.468420 -> initscore=-0.126488
[LightGBM] [Info] Start training from score -0.126488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with posit

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

C:\Users\user\Anaconda3\lib\site-packages\lightgbm\engine.py:148: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[LightGBM] [Fatal] Could not open dataset/
Traceback (most recent call last):
  File "classify_binaries.py", line 37, in <module>
    main()
  File "classify_binaries.py", line 20, in main
    lgbm_model = lgb.Booster(model_file=args.modelpath)
  File "C:\Users\user\Anaconda3\lib\site-packages\lightgbm\basic.py", line 1744, in __init__
    ctypes.byref(self.handle)))
  File "C:\Users\user\Anaconda3\lib\site-packages\lightgbm\basic.py", line 45, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Could not open dataset/


1.734375


In [ ]:
ember.create_vectorized_features("dataset/")
ember.create_metadata("dataset/")

Vectorizing training set


100%|████████████████████████████████████████████████████████████████████████| 900000/900000 [12:36<00:00, 1189.04it/s]


Vectorizing test set


100%|████████████████████████████████████████████████████████████████████████| 200000/200000 [02:01<00:00, 1650.83it/s]


sha256 appeared subset  \
0        0abb4fda7d5b13801d63bee53e5e256be43e141faa077a...  2006-12  train   
1        d4206650743b3d519106dea10a38a55c30467c3d9f7875...  2006-12  train   
2        c9cafff8a596ba8a80bafb4ba8ae6f2ef3329d95b85f15...  2007-01  train   
3        7f513818bcc276c531af2e641c597744da807e21cc1160...  2007-02  train   
4        ca65e1c387a4cc9e7d8a8ce12bf1bcf9f534c9032b9d95...  2007-02  train   
...                                                    ...      ...    ...   
1099995  fffe314f23cee3a68ccab272934877d3bc18ec3bd905df...  2017-12   test   
1099996  fffe7a1b23e04facc9ca91a93ac4a34e8b3040e023dbde...  2017-12   test   
1099997  fffe801f51e7ec931515aa49a3d157a9c0fbcdca8c9d80...  2017-12   test   
1099998  fffe92f9593649c4a7050302368189de45e2c1c06b04ea...  2017-12   test   
1099999  ffffb259a4c5e25ae1437af59caafb718cf8879187cc8c...  2017-12   test   

         label  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
1099995      0  
1099996      1  
1099997      0  
1099998      1  
1099999      1  

[1100000 rows x 4 columns]

In [ ]:
X_train, y_train, X_test, y_test = ember.read_vectorized_features("dataset/")

In [ ]:
import numpy as np
print(np.unique(X_train,return_counts = True))
print(np.unique(X_test,return_counts = True))

(array([-4.2949645e+09, -4.2910016e+09, -4.2782554e+09, ...,
        4.2954752e+09,  4.2971300e+09,  8.3034742e+09], dtype=float32), array([1, 2, 1, ..., 1, 1, 1], dtype=int64))
(array([-4.2949647e+09, -1.5659224e+09, -8.8280832e+08, ...,
        4.2948150e+09,  4.2949673e+09,  4.2954056e+09], dtype=float32), array([ 1,  1,  1, ...,  1, 13,  1], dtype=int64))


In [ ]:
import numpy as np
print(np.unique(y_train,return_counts = True))
print(np.unique(y_test,return_counts = True))

(array([-1.,  0.,  1.], dtype=float32), array([300000, 300000, 300000], dtype=int64))
(array([0., 1.], dtype=float32), array([100000, 100000], dtype=int64))


## Using LGB model

In [ ]:
lgbm_model = lgb.Booster(model_file="dataset/model.txt")


In [ ]:
y_test_pred = lgbm_model.predict(X_test)
y_train_pred = lgbm_model.predict(X_train)


In [ ]:
emberdf = ember.read_metadata("dataset/")

C:\Users\user\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [ ]:
emberdf["y_pred"] = np.hstack((y_train_pred, y_test_pred))

In [ ]:
def get_fpr(y_true, y_pred):
    nbenign = (y_true == 0).sum()
    nfalse = (y_pred[y_true == 0] == 1).sum()
    return nfalse / float(nbenign)

In [ ]:
emberdf.tail()

sha256 appeared subset  \
1099995  fffe314f23cee3a68ccab272934877d3bc18ec3bd905df...  2017-12   test   
1099996  fffe7a1b23e04facc9ca91a93ac4a34e8b3040e023dbde...  2017-12   test   
1099997  fffe801f51e7ec931515aa49a3d157a9c0fbcdca8c9d80...  2017-12   test   
1099998  fffe92f9593649c4a7050302368189de45e2c1c06b04ea...  2017-12   test   
1099999  ffffb259a4c5e25ae1437af59caafb718cf8879187cc8c...  2017-12   test   

         label        y_pred  
1099995      0  2.453346e-10  
1099996      1  1.000000e+00  
1099997      0  2.597864e-08  
1099998      1  1.000000e+00  
1099999      1  1.000000e+00

In [ ]:
traindf = emberdf[emberdf["subset"] == "train"]
testdf = emberdf[emberdf["subset"] == "test"]

In [ ]:
from sklearn.metrics import roc_auc_score, roc_curve

def find_threshold(y_true, y_pred, fpr_target):
    thresh = 0.0
    fpr = get_fpr(y_true, y_pred > thresh)
    while fpr > fpr_target and thresh < 1.0:
        thresh += 0.0001
        fpr = get_fpr(y_true, y_pred > thresh)
    return thresh, fpr

testdf = emberdf[emberdf["subset"] == "test"]
print("ROC AUC:", roc_auc_score(testdf.label, testdf.y_pred))
print()

threshold, fpr = find_threshold(testdf.label, testdf.y_pred, 0.01)
fnr = (testdf.y_pred[testdf.label == 1] < threshold).sum() / float((testdf.label == 1).sum())
print("Ember Model Performance at 1% FPR:")
print("Threshold: {:.3f}".format(threshold))
print("False Positive Rate: {:.3f}%".format(fpr * 100))
print("False Negative Rate: {:.3f}%".format(fnr * 100))
print("Detection Rate: {}%".format(100 - fnr * 100))
print()

threshold, fpr = find_threshold(testdf.label, testdf.y_pred, 0.001)
fnr = (testdf.y_pred[testdf.label == 1] < threshold).sum() / float((testdf.label == 1).sum())
print("Ember Model Performance at 0.1% FPR:")
print("Threshold: {:.3f}".format(threshold))
print("False Positive Rate: {:.3f}%".format(fpr * 100))
print("False Negative Rate: {:.3f}%".format(fnr * 100))
print("Detection Rate: {}%".format(100 - fnr * 100))

ROC AUC: 0.9997670127

Ember Model Performance at 1% FPR:
Threshold: 0.006
False Positive Rate: 0.998%
False Negative Rate: 0.431%
Detection Rate: 99.569%

Ember Model Performance at 0.1% FPR:
Threshold: 0.952
False Positive Rate: 0.100%
False Negative Rate: 1.270%
Detection Rate: 98.73%


In [ ]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(900000, 2381) (900000,)
(200000, 2381) (200000,)


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

## Using neural nets 

In [ ]:
model = Sequential()
model.add(Dense(128, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(64, activation='relu')) 
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')

#monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto',restore_best_weights=True)
model.fit(X_train,y_train,verbose=2,epochs=10)








Epoch 1/10





 - 196s - loss: 0.5369
Epoch 2/10
 - 152s - loss: 0.5222
Epoch 3/10
 - 154s - loss: 0.5146
Epoch 4/10
 - 148s - loss: 0.5102
Epoch 5/10
 - 152s - loss: 0.5067
Epoch 6/10
 - 151s - loss: 0.5044
Epoch 7/10
 - 150s - loss: 0.5017
Epoch 8/10
 - 148s - loss: 0.4998
Epoch 9/10
 - 149s - loss: 0.4982
Epoch 10/10
 - 152s - loss: 0.4950


In [ ]:
# evaluate the model
train_acc = model.evaluate(X_train, y_train, verbose = 2)
test_acc = model.evaluate(X_test,y_test,verbose = 2)
print('Train: %.3f, Test: %.3f' % (train_acc, test_acc))

Train: 0.489, Test: 0.396


In [ ]:
# calculating  accuracy

y_predict = model.predict(X_test, verbose=2)
y_classes = model.predict_classes(X_test, verbose=2)

In [ ]:
print(y_predict.shape, y_classes.shape)

(200000, 1) (200000, 1)


In [ ]:
# reduce to 1d array
y_predict = y_predict[:, 0]
y_classes = y_classes[:, 0]

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_test, y_classes)
print('Accuracy: %f' % accuracy)


Accuracy: 0.500530


In [ ]:
save_path = r"C:\Users\user\Desktop\AI & cybersecurity\AI midterm\ember"

model.save_weights(os.path.join(save_path,"dnn_model_weights.h5"))

# save neural network structure to JSON (no weights)
model_json = model.to_json()
with open(os.path.join(save_path,"dnn_model.json"), "w") as json_file:
    json_file.write(model_json)